{
 "title": "Chameleon",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "SELECT\n  (data->>'src_ip')\nFROM\n  sniffer_table\nLIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "SSH Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%ssh_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "HTTP Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%http_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "HTTPS Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%https_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Opened Ports",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  (data->>'dst_port')::int as port,\n  (data->>'src_ip')\nFROM\n  sniffer_table\nWHERE\n  $__timeFilter(date) and data->>'action' LIKE '%tcpscan%' and (data->>'src_ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "ICMP Payload",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT data->>'src_ip' as ip,\n       data->>'ICMP_MSG' as payload\nFROM   sniffer_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%icmp%' AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "FTP Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%ftp_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "SMTP Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%smtp_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "POP3 Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%pop3_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "DNS Payload",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT data->>'ip' as ip,\n       data->>'payload' as payload\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%dns_server%' AND (data->>'ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "RDP Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%rdp_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "SMB Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%smb_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Postgres Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%postgres_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Proxy Payload",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT data->>'ip' as ip,\n       data->>'payload' as payload\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%http_proxy_server%' AND (data->>'ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Telnet Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%telnet_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "SOCKS5 Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%socks5_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "MySQL Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%mysql_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  (data->>'bytes_sent')::int as bytes_sent,\n  (data->>'bytes_recv')::int as bytes_recv,\n  (data->>'packets_sent')::int as packets_sent,\n  (data->>'packets_recv')::int as packets_recv\nFROM\n  system_table\nWHERE\n  $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "VNC Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%vnc_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "Redis Login",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) filter (WHERE data->>'status' LIKE '%success%') AS success,\n       count(id) filter (WHERE data->>'status' LIKE '%failed%') AS failed\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'server' LIKE '%redis_server%' AND data->>'status'  <> '' AND (data->>'ip') LIKE '%$IP%'"
    }
   ]
  },
  {
   "title": "TCP Payload",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT data->>'src_ip' as ip,\n       data->>'raw_payload' as payload\nFROM   sniffer_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%tcppayload%' AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "All Creds",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT data->>'ip' as ip,\n       data->>'username' as username,\n       data->>'password' as password,\n       data->>'server' as server\nFROM   servers_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%login%' AND data->>'ip' <> ''  AND (data->>'ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  (data->'sniffer'->>'memory')::float as sniffer,\n  (data->'ftp_server'->>'memory')::float as ftp,\n  (data->'dns_server'->>'memory')::float as dns,\n  (data->'http_server'->>'memory')::float as http,\n  (data->'https_server'->>'memory')::float as https,\n  (data->'http_proxy_server'->>'memory')::float as http,\n  (data->'pop3_server'->>'memory')::float as pop3,\n  (data->'imap_server'->>'memory')::float as imap,\n  (data->'rdp_server'->>'memory')::float as rdp,\n  (data->'smb_server'->>'memory')::float as smb,\n  (data->'smtp_server'->>'memory')::float as smtp,\n  (data->'vnc_server'->>'memory')::float as vnc,\n  (data->'ssh_server'->>'memory')::float as ssh,\n  (data->'socks5_server'->>'memory')::float as socks5,\n  (data->'telnet_server'->>'memory')::float as telnet,\n  (data->'redis_server'->>'memory')::float as redis,\n  (data->'mysql_server'->>'memory')::float as mysql,\n  (data->'postgres_server'->>'memory')::float as postgres\nFROM\n  system_table\n  system_table\nWHERE\n  $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "UDP Payload",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT data->>'ip' as ip,\n       data->>'raw_payload' as payload\nFROM   sniffer_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%udppayload%' AND (data->>'src_ip') LIKE '%$IP%'\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Loose Creds",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT data->>'payload' as payload\nFROM   sniffer_table\nWHERE  $__timeFilter(date) AND data->>'action' LIKE '%creds_check%' AND data->>'payload' <> ''\nORDER BY id ASC"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(date),\n  (data->'sniffer'->>'cpu')::float as sniffer,\n  (data->'ftp_server'->>'cpu')::float as ftp,\n  (data->'dns_server'->>'cpu')::float as dns,\n  (data->'http_server'->>'cpu')::float as http,\n  (data->'https_server'->>'cpu')::float as https,\n  (data->'http_proxy_server'->>'cpu')::float as http,\n  (data->'pop3_server'->>'cpu')::float as pop3,\n  (data->'imap_server'->>'cpu')::float as imap,\n  (data->'rdp_server'->>'cpu')::float as rdp,\n  (data->'smb_server'->>'cpu')::float as smb,\n  (data->'smtp_server'->>'cpu')::float as smtp,\n  (data->'vnc_server'->>'cpu')::float as vnc,\n  (data->'ssh_server'->>'cpu')::float as ssh,\n  (data->'socks5_server'->>'cpu')::float as socks5,\n  (data->'telnet_server'->>'cpu')::float as telnet,\n  (data->'redis_server'->>'cpu')::float as redis,\n  (data->'mysql_server'->>'cpu')::float as mysql,\n  (data->'postgres_server'->>'cpu')::float as postgres\nFROM\n  system_table\nWHERE\n  $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT $__time(date),\n       data->>'type' as type\nFROM   errors_table\nWHERE  $__timeFilter(date) AND data->>'type' <> ''\n"
    }
   ]
  }
 ]
}